// // ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison

// // WARNING: This code is auto-generated by Supadart.
// // WARNING: Modifications may be overwritten. Please make changes in the SupaDart configuration.

// // SDK
// import 'package:supabase_flutter/supabase_flutter.dart';

// // INTL is an official package from Dart and is used for parsing dates
// // flutter pub add intl or dart pub add intl
// import 'package:intl/intl.dart';

// import 'dart:convert';

// // Supadart Class
// abstract class SupadartClass<T> {
//   static Map<String, dynamic> insert(Map<String, dynamic> data) {
//     throw UnimplementedError();
//   }

//   static Map<String, dynamic> update(Map<String, dynamic> data) {
//     throw UnimplementedError();
//   }

//   factory SupadartClass.fromJson(Map<String, dynamic> json) {
//     throw UnimplementedError();
//   }

//   static converter(List<Map<String, dynamic>> data) {
//     throw UnimplementedError();
//   }

//   static converterSingle(Map<String, dynamic> data) {
//     throw UnimplementedError();
//   }
// }

// // Supabase Client Extension
// extension SupadartClient on SupabaseClient {
//   SupabaseQueryBuilder get attraction_types => from('attraction_types');
//   SupabaseQueryBuilder get trip_summaries => from('trip_summaries');
//   SupabaseQueryBuilder get user_preferences => from('user_preferences');
//   SupabaseQueryBuilder get trips => from('trips');
//   SupabaseQueryBuilder get trip_schedule => from('trip_schedule');
//   SupabaseQueryBuilder get profiles => from('profiles');
//   SupabaseQueryBuilder get locations => from('locations');
//   SupabaseQueryBuilder get attractions => from('attractions');
//   SupabaseQueryBuilder get travel_types => from('travel_types');
//   SupabaseQueryBuilder get todo_lists => from('todo_lists');
//   SupabaseQueryBuilder get trip_members => from('trip_members');
// }

// // Supabase Storage Client Extension
// extension SupadartStorageClient on SupabaseStorageClient {}

// // Enums
// enum GENDERS { male, female, others }

// // Utils
// class AttractionTypes implements SupadartClass<AttractionTypes> {
//   final int id;
//   final DateTime createdAt;
//   final int attractionId;
//   final String travelTypeId;
//   final String typeName;

//   const AttractionTypes({
//     required this.id,
//     required this.createdAt,
//     required this.attractionId,
//     required this.travelTypeId,
//     required this.typeName,
//   });

//   static String get table_name => 'attraction_types';
//   static String get c_id => 'id';
//   static String get c_createdAt => 'created_at';
//   static String get c_attractionId => 'attraction_id';
//   static String get c_travelTypeId => 'travel_type_id';
//   static String get c_typeName => 'type_name';

//   static List<AttractionTypes> converter(List<Map<String, dynamic>> data) {
//     return data.map(AttractionTypes.fromJson).toList();
//   }

//   static AttractionTypes converterSingle(Map<String, dynamic> data) {
//     return AttractionTypes.fromJson(data);
//   }

//   static Map<String, dynamic> _generateMap({
//     int? id,
//     DateTime? createdAt,
//     int? attractionId,
//     String? travelTypeId,
//     String? typeName,
//   }) {
//     return {
//       if (id != null) 'id': id.toString(),
//       if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
//       if (attractionId != null) 'attraction_id': attractionId.toString(),
//       if (travelTypeId != null) 'travel_type_id': travelTypeId,
//       if (typeName != null) 'type_name': typeName,
//     };
//   }

//   static Map<String, dynamic> insert({
//     int? id,
//     DateTime? createdAt,
//     required int attractionId,
//     required String travelTypeId,
//     String? typeName,
//   }) {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       attractionId: attractionId,
//       travelTypeId: travelTypeId,
//       typeName: typeName,
//     );
//   }

//   static Map<String, dynamic> update({
//     int? id,
//     DateTime? createdAt,
//     int? attractionId,
//     String? travelTypeId,
//     String? typeName,
//   }) {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       attractionId: attractionId,
//       travelTypeId: travelTypeId,
//       typeName: typeName,
//     );
//   }

//   factory AttractionTypes.fromJson(Map<String, dynamic> jsonn) {
//     return AttractionTypes(
//       id: jsonn['id'] != null ? int.parse(jsonn['id'].toString()) : int.from(0),
//       createdAt: jsonn['created_at'] != null
//           ? DateTime.parse(jsonn['created_at'].toString())
//           : DateTime.fromMillisecondsSinceEpoch(0),
//       attractionId: jsonn['attraction_id'] != null
//           ? int.parse(jsonn['attraction_id'].toString())
//           : int.from(0),
//       travelTypeId: jsonn['travel_type_id'] != null
//           ? jsonn['travel_type_id'].toString()
//           : '',
//       typeName: jsonn['type_name'] != null ? jsonn['type_name'].toString() : '',
//     );
//   }

//   Map<String, dynamic> toJson() {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       attractionId: attractionId,
//       travelTypeId: travelTypeId,
//       typeName: typeName,
//     );
//   }

//   AttractionTypes copyWith({
//     int? id,
//     DateTime? createdAt,
//     int? attractionId,
//     String? travelTypeId,
//     String? typeName,
//   }) {
//     return AttractionTypes(
//       id: id ?? this.id,
//       createdAt: createdAt ?? this.createdAt,
//       attractionId: attractionId ?? this.attractionId,
//       travelTypeId: travelTypeId ?? this.travelTypeId,
//       typeName: typeName ?? this.typeName,
//     );
//   }
// }

// class TripSummaries implements SupadartClass<TripSummaries> {
//   final int id;
//   final DateTime createdAt;
//   final String? tripId;
//   final Map<String, dynamic>? summary;

//   const TripSummaries({
//     required this.id,
//     required this.createdAt,
//     this.tripId,
//     this.summary,
//   });

//   static String get table_name => 'trip_summaries';
//   static String get c_id => 'id';
//   static String get c_createdAt => 'created_at';
//   static String get c_tripId => 'trip_id';
//   static String get c_summary => 'summary';

//   static List<TripSummaries> converter(List<Map<String, dynamic>> data) {
//     return data.map(TripSummaries.fromJson).toList();
//   }

//   static TripSummaries converterSingle(Map<String, dynamic> data) {
//     return TripSummaries.fromJson(data);
//   }

//   static Map<String, dynamic> _generateMap({
//     int? id,
//     DateTime? createdAt,
//     String? tripId,
//     Map<String, dynamic>? summary,
//   }) {
//     return {
//       if (id != null) 'id': id.toString(),
//       if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
//       if (tripId != null) 'trip_id': tripId,
//       if (summary != null) 'summary': summary,
//     };
//   }

//   static Map<String, dynamic> insert({
//     int? id,
//     DateTime? createdAt,
//     String? tripId,
//     Map<String, dynamic>? summary,
//   }) {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       tripId: tripId,
//       summary: summary,
//     );
//   }

//   static Map<String, dynamic> update({
//     int? id,
//     DateTime? createdAt,
//     String? tripId,
//     Map<String, dynamic>? summary,
//   }) {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       tripId: tripId,
//       summary: summary,
//     );
//   }

//   factory TripSummaries.fromJson(Map<String, dynamic> jsonn) {
//     return TripSummaries(
//       id: jsonn['id'] != null ? int.parse(jsonn['id'].toString()) : int.from(0),
//       createdAt: jsonn['created_at'] != null
//           ? DateTime.parse(jsonn['created_at'].toString())
//           : DateTime.fromMillisecondsSinceEpoch(0),
//       tripId: jsonn['trip_id'] != null ? jsonn['trip_id'].toString() : '',
//       summary: jsonn['summary'] != null
//           ? jsonn['summary'] as Map<String, dynamic>
//           : <String, dynamic>{},
//     );
//   }

//   Map<String, dynamic> toJson() {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       tripId: tripId,
//       summary: summary,
//     );
//   }

//   TripSummaries copyWith({
//     int? id,
//     DateTime? createdAt,
//     String? tripId,
//     Map<String, dynamic>? summary,
//   }) {
//     return TripSummaries(
//       id: id ?? this.id,
//       createdAt: createdAt ?? this.createdAt,
//       tripId: tripId ?? this.tripId,
//       summary: summary ?? this.summary,
//     );
//   }
// }

// class UserPreferences implements SupadartClass<UserPreferences> {
//   final int id;
//   final DateTime createdAt;
//   final String userId;
//   final double budget;
//   final Map<String, dynamic> prefsDf;
//   final double avgRating;
//   final int ratingCount;

//   const UserPreferences({
//     required this.id,
//     required this.createdAt,
//     required this.userId,
//     required this.budget,
//     required this.prefsDf,
//     required this.avgRating,
//     required this.ratingCount,
//   });

//   static String get table_name => 'user_preferences';
//   static String get c_id => 'id';
//   static String get c_createdAt => 'created_at';
//   static String get c_userId => 'user_id';
//   static String get c_budget => 'budget';
//   static String get c_prefsDf => 'prefs_df';
//   static String get c_avgRating => 'avg_rating';
//   static String get c_ratingCount => 'rating_count';

//   static List<UserPreferences> converter(List<Map<String, dynamic>> data) {
//     return data.map(UserPreferences.fromJson).toList();
//   }

//   static UserPreferences converterSingle(Map<String, dynamic> data) {
//     return UserPreferences.fromJson(data);
//   }

//   static Map<String, dynamic> _generateMap({
//     int? id,
//     DateTime? createdAt,
//     String? userId,
//     double? budget,
//     Map<String, dynamic>? prefsDf,
//     double? avgRating,
//     int? ratingCount,
//   }) {
//     return {
//       if (id != null) 'id': id.toString(),
//       if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
//       if (userId != null) 'user_id': userId,
//       if (budget != null) 'budget': budget.toString(),
//       if (prefsDf != null) 'prefs_df': prefsDf,
//       if (avgRating != null) 'avg_rating': avgRating.toString(),
//       if (ratingCount != null) 'rating_count': ratingCount.toString(),
//     };
//   }

//   static Map<String, dynamic> insert({
//     int? id,
//     DateTime? createdAt,
//     String? userId,
//     required double budget,
//     required Map<String, dynamic> prefsDf,
//     required double avgRating,
//     required int ratingCount,
//   }) {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       userId: userId,
//       budget: budget,
//       prefsDf: prefsDf,
//       avgRating: avgRating,
//       ratingCount: ratingCount,
//     );
//   }

//   static Map<String, dynamic> update({
//     int? id,
//     DateTime? createdAt,
//     String? userId,
//     double? budget,
//     Map<String, dynamic>? prefsDf,
//     double? avgRating,
//     int? ratingCount,
//   }) {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       userId: userId,
//       budget: budget,
//       prefsDf: prefsDf,
//       avgRating: avgRating,
//       ratingCount: ratingCount,
//     );
//   }

//   factory UserPreferences.fromJson(Map<String, dynamic> jsonn) {
//     return UserPreferences(
//       id: jsonn['id'] != null ? int.parse(jsonn['id'].toString()) : int.from(0),
//       createdAt: jsonn['created_at'] != null
//           ? DateTime.parse(jsonn['created_at'].toString())
//           : DateTime.fromMillisecondsSinceEpoch(0),
//       userId: jsonn['user_id'] != null ? jsonn['user_id'].toString() : '',
//       budget: jsonn['budget'] != null
//           ? double.parse(jsonn['budget'].toString())
//           : 0.0,
//       prefsDf: jsonn['prefs_df'] != null
//           ? jsonn['prefs_df'] as Map<String, dynamic>
//           : <String, dynamic>{},
//       avgRating: jsonn['avg_rating'] != null
//           ? double.parse(jsonn['avg_rating'].toString())
//           : 0.0,
//       ratingCount: jsonn['rating_count'] != null
//           ? int.parse(jsonn['rating_count'].toString())
//           : int.from(0),
//     );
//   }

//   Map<String, dynamic> toJson() {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       userId: userId,
//       budget: budget,
//       prefsDf: prefsDf,
//       avgRating: avgRating,
//       ratingCount: ratingCount,
//     );
//   }

//   UserPreferences copyWith({
//     int? id,
//     DateTime? createdAt,
//     String? userId,
//     double? budget,
//     Map<String, dynamic>? prefsDf,
//     double? avgRating,
//     int? ratingCount,
//   }) {
//     return UserPreferences(
//       id: id ?? this.id,
//       createdAt: createdAt ?? this.createdAt,
//       userId: userId ?? this.userId,
//       budget: budget ?? this.budget,
//       prefsDf: prefsDf ?? this.prefsDf,
//       avgRating: avgRating ?? this.avgRating,
//       ratingCount: ratingCount ?? this.ratingCount,
//     );
//   }
// }

// class Trips implements SupadartClass<Trips> {
//   final String id;
//   final DateTime createdAt;
//   final String title;
//   final DateTime startDate;
//   final DateTime endDate;
//   final int maxMember;
//   final int locationId;
//   final String ownerId;

//   const Trips({
//     required this.id,
//     required this.createdAt,
//     required this.title,
//     required this.startDate,
//     required this.endDate,
//     required this.maxMember,
//     required this.locationId,
//     required this.ownerId,
//   });

//   static String get table_name => 'trips';
//   static String get c_id => 'id';
//   static String get c_createdAt => 'created_at';
//   static String get c_title => 'title';
//   static String get c_startDate => 'start_date';
//   static String get c_endDate => 'end_date';
//   static String get c_maxMember => 'max_member';
//   static String get c_locationId => 'location_id';
//   static String get c_ownerId => 'owner_id';

//   static List<Trips> converter(List<Map<String, dynamic>> data) {
//     return data.map(Trips.fromJson).toList();
//   }

//   static Trips converterSingle(Map<String, dynamic> data) {
//     return Trips.fromJson(data);
//   }

//   static Map<String, dynamic> _generateMap({
//     String? id,
//     DateTime? createdAt,
//     String? title,
//     DateTime? startDate,
//     DateTime? endDate,
//     int? maxMember,
//     int? locationId,
//     String? ownerId,
//   }) {
//     return {
//       if (id != null) 'id': id,
//       if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
//       if (title != null) 'title': title,
//       if (startDate != null) 'start_date': startDate.toIso8601String(),
//       if (endDate != null) 'end_date': endDate.toIso8601String(),
//       if (maxMember != null) 'max_member': maxMember,
//       if (locationId != null) 'location_id': locationId.toString(),
//       if (ownerId != null) 'owner_id': ownerId,
//     };
//   }

//   static Map<String, dynamic> insert({
//     String? id,
//     DateTime? createdAt,
//     required String title,
//     required DateTime startDate,
//     required DateTime endDate,
//     required int maxMember,
//     required int locationId,
//     required String ownerId,
//   }) {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       title: title,
//       startDate: startDate,
//       endDate: endDate,
//       maxMember: maxMember,
//       locationId: locationId,
//       ownerId: ownerId,
//     );
//   }

//   static Map<String, dynamic> update({
//     String? id,
//     DateTime? createdAt,
//     String? title,
//     DateTime? startDate,
//     DateTime? endDate,
//     int? maxMember,
//     int? locationId,
//     String? ownerId,
//   }) {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       title: title,
//       startDate: startDate,
//       endDate: endDate,
//       maxMember: maxMember,
//       locationId: locationId,
//       ownerId: ownerId,
//     );
//   }

//   factory Trips.fromJson(Map<String, dynamic> jsonn) {
//     return Trips(
//       id: jsonn['id'] != null ? jsonn['id'].toString() : '',
//       createdAt: jsonn['created_at'] != null
//           ? DateTime.parse(jsonn['created_at'].toString())
//           : DateTime.fromMillisecondsSinceEpoch(0),
//       title: jsonn['title'] != null ? jsonn['title'].toString() : '',
//       startDate: jsonn['start_date'] != null
//           ? DateTime.parse(jsonn['start_date'].toString())
//           : DateTime.fromMillisecondsSinceEpoch(0),
//       endDate: jsonn['end_date'] != null
//           ? DateTime.parse(jsonn['end_date'].toString())
//           : DateTime.fromMillisecondsSinceEpoch(0),
//       maxMember: jsonn['max_member'] != null
//           ? int.parse(jsonn['max_member'].toString())
//           : 0,
//       locationId: jsonn['location_id'] != null
//           ? int.parse(jsonn['location_id'].toString())
//           : int.from(0),
//       ownerId: jsonn['owner_id'] != null ? jsonn['owner_id'].toString() : '',
//     );
//   }

//   Map<String, dynamic> toJson() {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       title: title,
//       startDate: startDate,
//       endDate: endDate,
//       maxMember: maxMember,
//       locationId: locationId,
//       ownerId: ownerId,
//     );
//   }

//   Trips copyWith({
//     String? id,
//     DateTime? createdAt,
//     String? title,
//     DateTime? startDate,
//     DateTime? endDate,
//     int? maxMember,
//     int? locationId,
//     String? ownerId,
//   }) {
//     return Trips(
//       id: id ?? this.id,
//       createdAt: createdAt ?? this.createdAt,
//       title: title ?? this.title,
//       startDate: startDate ?? this.startDate,
//       endDate: endDate ?? this.endDate,
//       maxMember: maxMember ?? this.maxMember,
//       locationId: locationId ?? this.locationId,
//       ownerId: ownerId ?? this.ownerId,
//     );
//   }
// }

// class TripSchedule implements SupadartClass<TripSchedule> {
//   final int id;
//   final DateTime createdAt;
//   final String? tripId;
//   final String? title;
//   final DateTime? time;
//   final int? attractionId;
//   final Map<String, dynamic>? placeMetadata;

//   const TripSchedule({
//     required this.id,
//     required this.createdAt,
//     this.tripId,
//     this.title,
//     this.time,
//     this.attractionId,
//     this.placeMetadata,
//   });

//   static String get table_name => 'trip_schedule';
//   static String get c_id => 'id';
//   static String get c_createdAt => 'created_at';
//   static String get c_tripId => 'trip_id';
//   static String get c_title => 'title';
//   static String get c_time => 'time';
//   static String get c_attractionId => 'attraction_id';
//   static String get c_placeMetadata => 'place_metadata';

//   static List<TripSchedule> converter(List<Map<String, dynamic>> data) {
//     return data.map(TripSchedule.fromJson).toList();
//   }

//   static TripSchedule converterSingle(Map<String, dynamic> data) {
//     return TripSchedule.fromJson(data);
//   }

//   static Map<String, dynamic> _generateMap({
//     int? id,
//     DateTime? createdAt,
//     String? tripId,
//     String? title,
//     DateTime? time,
//     int? attractionId,
//     Map<String, dynamic>? placeMetadata,
//   }) {
//     return {
//       if (id != null) 'id': id.toString(),
//       if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
//       if (tripId != null) 'trip_id': tripId,
//       if (title != null) 'title': title,
//       if (time != null) 'time': DateFormat('HH:mm:ssZ').format(time.toLocal()),
//       if (attractionId != null) 'attraction_id': attractionId.toString(),
//       if (placeMetadata != null) 'place_metadata': placeMetadata,
//     };
//   }

//   static Map<String, dynamic> insert({
//     int? id,
//     DateTime? createdAt,
//     String? tripId,
//     String? title,
//     DateTime? time,
//     int? attractionId,
//     Map<String, dynamic>? placeMetadata,
//   }) {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       tripId: tripId,
//       title: title,
//       time: time,
//       attractionId: attractionId,
//       placeMetadata: placeMetadata,
//     );
//   }

//   static Map<String, dynamic> update({
//     int? id,
//     DateTime? createdAt,
//     String? tripId,
//     String? title,
//     DateTime? time,
//     int? attractionId,
//     Map<String, dynamic>? placeMetadata,
//   }) {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       tripId: tripId,
//       title: title,
//       time: time,
//       attractionId: attractionId,
//       placeMetadata: placeMetadata,
//     );
//   }

//   factory TripSchedule.fromJson(Map<String, dynamic> jsonn) {
//     return TripSchedule(
//       id: jsonn['id'] != null ? int.parse(jsonn['id'].toString()) : int.from(0),
//       createdAt: jsonn['created_at'] != null
//           ? DateTime.parse(jsonn['created_at'].toString())
//           : DateTime.fromMillisecondsSinceEpoch(0),
//       tripId: jsonn['trip_id'] != null ? jsonn['trip_id'].toString() : '',
//       title: jsonn['title'] != null ? jsonn['title'].toString() : '',
//       time: jsonn['time'] != null
//           ? DateTime.parse("1970-01-01T${jsonn['time']}").toLocal()
//           : DateTime.fromMillisecondsSinceEpoch(0),
//       attractionId: jsonn['attraction_id'] != null
//           ? int.parse(jsonn['attraction_id'].toString())
//           : int.from(0),
//       placeMetadata: jsonn['place_metadata'] != null
//           ? jsonn['place_metadata'] as Map<String, dynamic>
//           : <String, dynamic>{},
//     );
//   }

//   Map<String, dynamic> toJson() {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       tripId: tripId,
//       title: title,
//       time: time,
//       attractionId: attractionId,
//       placeMetadata: placeMetadata,
//     );
//   }

//   TripSchedule copyWith({
//     int? id,
//     DateTime? createdAt,
//     String? tripId,
//     String? title,
//     DateTime? time,
//     int? attractionId,
//     Map<String, dynamic>? placeMetadata,
//   }) {
//     return TripSchedule(
//       id: id ?? this.id,
//       createdAt: createdAt ?? this.createdAt,
//       tripId: tripId ?? this.tripId,
//       title: title ?? this.title,
//       time: time ?? this.time,
//       attractionId: attractionId ?? this.attractionId,
//       placeMetadata: placeMetadata ?? this.placeMetadata,
//     );
//   }
// }

// class Profiles implements SupadartClass<Profiles> {
//   final String id;
//   final GENDERS? gender;
//   final String email;
//   final DateTime? dob;
//   final String? firstName;
//   final String? lastName;
//   final String? phone;
//   final String? avatarUrl;

//   const Profiles({
//     required this.id,
//     this.gender,
//     required this.email,
//     this.dob,
//     this.firstName,
//     this.lastName,
//     this.phone,
//     this.avatarUrl,
//   });

//   static String get table_name => 'profiles';
//   static String get c_id => 'id';
//   static String get c_gender => 'gender';
//   static String get c_email => 'email';
//   static String get c_dob => 'dob';
//   static String get c_firstName => 'first_name';
//   static String get c_lastName => 'last_name';
//   static String get c_phone => 'phone';
//   static String get c_avatarUrl => 'avatar_url';

//   static List<Profiles> converter(List<Map<String, dynamic>> data) {
//     return data.map(Profiles.fromJson).toList();
//   }

//   static Profiles converterSingle(Map<String, dynamic> data) {
//     return Profiles.fromJson(data);
//   }

//   static Map<String, dynamic> _generateMap({
//     String? id,
//     GENDERS? gender,
//     String? email,
//     DateTime? dob,
//     String? firstName,
//     String? lastName,
//     String? phone,
//     String? avatarUrl,
//   }) {
//     return {
//       if (id != null) 'id': id,
//       if (gender != null) 'gender': gender.toString().split('.').last,
//       if (email != null) 'email': email,
//       if (dob != null) 'dob': dob.toIso8601String(),
//       if (firstName != null) 'first_name': firstName,
//       if (lastName != null) 'last_name': lastName,
//       if (phone != null) 'phone': phone,
//       if (avatarUrl != null) 'avatar_url': avatarUrl,
//     };
//   }

//   static Map<String, dynamic> insert({
//     String? id,
//     GENDERS? gender,
//     required String email,
//     DateTime? dob,
//     String? firstName,
//     String? lastName,
//     String? phone,
//     String? avatarUrl,
//   }) {
//     return _generateMap(
//       id: id,
//       gender: gender,
//       email: email,
//       dob: dob,
//       firstName: firstName,
//       lastName: lastName,
//       phone: phone,
//       avatarUrl: avatarUrl,
//     );
//   }

//   static Map<String, dynamic> update({
//     String? id,
//     GENDERS? gender,
//     String? email,
//     DateTime? dob,
//     String? firstName,
//     String? lastName,
//     String? phone,
//     String? avatarUrl,
//   }) {
//     return _generateMap(
//       id: id,
//       gender: gender,
//       email: email,
//       dob: dob,
//       firstName: firstName,
//       lastName: lastName,
//       phone: phone,
//       avatarUrl: avatarUrl,
//     );
//   }

//   factory Profiles.fromJson(Map<String, dynamic> jsonn) {
//     return Profiles(
//       id: jsonn['id'] != null ? jsonn['id'].toString() : '',
//       gender: jsonn['gender'] != null
//           ? GENDERS.values.byName(jsonn['gender'].toString())
//           : GENDERS.values.first,
//       email: jsonn['email'] != null ? jsonn['email'].toString() : '',
//       dob: jsonn['dob'] != null
//           ? DateTime.parse(jsonn['dob'].toString())
//           : DateTime.fromMillisecondsSinceEpoch(0),
//       firstName:
//           jsonn['first_name'] != null ? jsonn['first_name'].toString() : '',
//       lastName: jsonn['last_name'] != null ? jsonn['last_name'].toString() : '',
//       phone: jsonn['phone'] != null ? jsonn['phone'].toString() : '',
//       avatarUrl:
//           jsonn['avatar_url'] != null ? jsonn['avatar_url'].toString() : '',
//     );
//   }

//   Map<String, dynamic> toJson() {
//     return _generateMap(
//       id: id,
//       gender: gender,
//       email: email,
//       dob: dob,
//       firstName: firstName,
//       lastName: lastName,
//       phone: phone,
//       avatarUrl: avatarUrl,
//     );
//   }

//   Profiles copyWith({
//     String? id,
//     GENDERS? gender,
//     String? email,
//     DateTime? dob,
//     String? firstName,
//     String? lastName,
//     String? phone,
//     String? avatarUrl,
//   }) {
//     return Profiles(
//       id: id ?? this.id,
//       gender: gender ?? this.gender,
//       email: email ?? this.email,
//       dob: dob ?? this.dob,
//       firstName: firstName ?? this.firstName,
//       lastName: lastName ?? this.lastName,
//       phone: phone ?? this.phone,
//       avatarUrl: avatarUrl ?? this.avatarUrl,
//     );
//   }
// }

// class Locations implements SupadartClass<Locations> {
//   final int id;
//   final DateTime createdAt;
//   final String name;
//   final List<String> images;
//   final String ename;
//   final String cover;
//   final double latitude;
//   final double longitude;
//   final int? parentId;

//   const Locations({
//     required this.id,
//     required this.createdAt,
//     required this.name,
//     required this.images,
//     required this.ename,
//     required this.cover,
//     required this.latitude,
//     required this.longitude,
//     this.parentId,
//   });

//   static String get table_name => 'locations';
//   static String get c_id => 'id';
//   static String get c_createdAt => 'created_at';
//   static String get c_name => 'name';
//   static String get c_images => 'images';
//   static String get c_ename => 'ename';
//   static String get c_cover => 'cover';
//   static String get c_latitude => 'latitude';
//   static String get c_longitude => 'longitude';
//   static String get c_parentId => 'parent_id';

//   static List<Locations> converter(List<Map<String, dynamic>> data) {
//     return data.map(Locations.fromJson).toList();
//   }

//   static Locations converterSingle(Map<String, dynamic> data) {
//     return Locations.fromJson(data);
//   }

//   static Map<String, dynamic> _generateMap({
//     int? id,
//     DateTime? createdAt,
//     String? name,
//     List<String>? images,
//     String? ename,
//     String? cover,
//     double? latitude,
//     double? longitude,
//     int? parentId,
//   }) {
//     return {
//       if (id != null) 'id': id.toString(),
//       if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
//       if (name != null) 'name': name,
//       if (images != null) 'images': images.map((e) => e).toList(),
//       if (ename != null) 'ename': ename,
//       if (cover != null) 'cover': cover,
//       if (latitude != null) 'latitude': latitude.toString(),
//       if (longitude != null) 'longitude': longitude.toString(),
//       if (parentId != null) 'parent_id': parentId.toString(),
//     };
//   }

//   static Map<String, dynamic> insert({
//     int? id,
//     DateTime? createdAt,
//     required String name,
//     required List<String> images,
//     required String ename,
//     required String cover,
//     required double latitude,
//     required double longitude,
//     int? parentId,
//   }) {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       name: name,
//       images: images,
//       ename: ename,
//       cover: cover,
//       latitude: latitude,
//       longitude: longitude,
//       parentId: parentId,
//     );
//   }

//   static Map<String, dynamic> update({
//     int? id,
//     DateTime? createdAt,
//     String? name,
//     List<String>? images,
//     String? ename,
//     String? cover,
//     double? latitude,
//     double? longitude,
//     int? parentId,
//   }) {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       name: name,
//       images: images,
//       ename: ename,
//       cover: cover,
//       latitude: latitude,
//       longitude: longitude,
//       parentId: parentId,
//     );
//   }

//   factory Locations.fromJson(Map<String, dynamic> jsonn) {
//     return Locations(
//       id: jsonn['id'] != null ? int.parse(jsonn['id'].toString()) : int.from(0),
//       createdAt: jsonn['created_at'] != null
//           ? DateTime.parse(jsonn['created_at'].toString())
//           : DateTime.fromMillisecondsSinceEpoch(0),
//       name: jsonn['name'] != null ? jsonn['name'].toString() : '',
//       images: jsonn['images'] != null
//           ? (jsonn['images'] as List<dynamic>).map((v) => v.toString()).toList()
//           : <String>[],
//       ename: jsonn['ename'] != null ? jsonn['ename'].toString() : '',
//       cover: jsonn['cover'] != null ? jsonn['cover'].toString() : '',
//       latitude: jsonn['latitude'] != null
//           ? double.parse(jsonn['latitude'].toString())
//           : 0.0,
//       longitude: jsonn['longitude'] != null
//           ? double.parse(jsonn['longitude'].toString())
//           : 0.0,
//       parentId: jsonn['parent_id'] != null
//           ? int.parse(jsonn['parent_id'].toString())
//           : int.from(0),
//     );
//   }

//   Map<String, dynamic> toJson() {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       name: name,
//       images: images,
//       ename: ename,
//       cover: cover,
//       latitude: latitude,
//       longitude: longitude,
//       parentId: parentId,
//     );
//   }

//   Locations copyWith({
//     int? id,
//     DateTime? createdAt,
//     String? name,
//     List<String>? images,
//     String? ename,
//     String? cover,
//     double? latitude,
//     double? longitude,
//     int? parentId,
//   }) {
//     return Locations(
//       id: id ?? this.id,
//       createdAt: createdAt ?? this.createdAt,
//       name: name ?? this.name,
//       images: images ?? this.images,
//       ename: ename ?? this.ename,
//       cover: cover ?? this.cover,
//       latitude: latitude ?? this.latitude,
//       longitude: longitude ?? this.longitude,
//       parentId: parentId ?? this.parentId,
//     );
//   }
// }

// class Attractions implements SupadartClass<Attractions> {
//   final int id;
//   final DateTime createdAt;
//   final String name;
//   final String? ename;
//   final String cover;
//   final List<String>? images;
//   final double hotScore;
//   final int? price;
//   final Map<String, dynamic>? rankInfo;
//   final double latitude;
//   final double longtitude;
//   final String? address;
//   final int locationId;
//   final List<Map<String, dynamic>>? openTimeRule;
//   final String description;
//   final String? phone;
//   final double? avgRating;
//   final int? ratingCount;

//   const Attractions({
//     required this.id,
//     required this.createdAt,
//     required this.name,
//     this.ename,
//     required this.cover,
//     this.images,
//     required this.hotScore,
//     this.price,
//     this.rankInfo,
//     required this.latitude,
//     required this.longtitude,
//     this.address,
//     required this.locationId,
//     this.openTimeRule,
//     required this.description,
//     this.phone,
//     this.avgRating,
//     this.ratingCount,
//   });

//   static String get table_name => 'attractions';
//   static String get c_id => 'id';
//   static String get c_createdAt => 'created_at';
//   static String get c_name => 'name';
//   static String get c_ename => 'ename';
//   static String get c_cover => 'cover';
//   static String get c_images => 'images';
//   static String get c_hotScore => 'hot_score';
//   static String get c_price => 'price';
//   static String get c_rankInfo => 'rank_info';
//   static String get c_latitude => 'latitude';
//   static String get c_longtitude => 'longtitude';
//   static String get c_address => 'address';
//   static String get c_locationId => 'location_id';
//   static String get c_openTimeRule => 'open_time_rule';
//   static String get c_description => 'description';
//   static String get c_phone => 'phone';
//   static String get c_avgRating => 'avg_rating';
//   static String get c_ratingCount => 'rating_count';

//   static List<Attractions> converter(List<Map<String, dynamic>> data) {
//     return data.map(Attractions.fromJson).toList();
//   }

//   static Attractions converterSingle(Map<String, dynamic> data) {
//     return Attractions.fromJson(data);
//   }

//   static Map<String, dynamic> _generateMap({
//     int? id,
//     DateTime? createdAt,
//     String? name,
//     String? ename,
//     String? cover,
//     List<String>? images,
//     double? hotScore,
//     int? price,
//     Map<String, dynamic>? rankInfo,
//     double? latitude,
//     double? longtitude,
//     String? address,
//     int? locationId,
//     List<Map<String, dynamic>>? openTimeRule,
//     String? description,
//     String? phone,
//     double? avgRating,
//     int? ratingCount,
//   }) {
//     return {
//       if (id != null) 'id': id.toString(),
//       if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
//       if (name != null) 'name': name,
//       if (ename != null) 'ename': ename,
//       if (cover != null) 'cover': cover,
//       if (images != null) 'images': images.map((e) => e).toList(),
//       if (hotScore != null) 'hot_score': hotScore,
//       if (price != null) 'price': price.toString(),
//       if (rankInfo != null) 'rank_info': rankInfo,
//       if (latitude != null) 'latitude': latitude.toString(),
//       if (longtitude != null) 'longtitude': longtitude.toString(),
//       if (address != null) 'address': address,
//       if (locationId != null) 'location_id': locationId.toString(),
//       if (openTimeRule != null)
//         'open_time_rule': openTimeRule.map((e) => jsonEncode(e)).toList(),
//       if (description != null) 'description': description,
//       if (phone != null) 'phone': phone,
//       if (avgRating != null) 'avg_rating': avgRating.toString(),
//       if (ratingCount != null) 'rating_count': ratingCount.toString(),
//     };
//   }

//   static Map<String, dynamic> insert({
//     int? id,
//     DateTime? createdAt,
//     required String name,
//     String? ename,
//     required String cover,
//     List<String>? images,
//     required double hotScore,
//     int? price,
//     Map<String, dynamic>? rankInfo,
//     required double latitude,
//     required double longtitude,
//     String? address,
//     required int locationId,
//     List<Map<String, dynamic>>? openTimeRule,
//     String? description,
//     String? phone,
//     double? avgRating,
//     int? ratingCount,
//   }) {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       name: name,
//       ename: ename,
//       cover: cover,
//       images: images,
//       hotScore: hotScore,
//       price: price,
//       rankInfo: rankInfo,
//       latitude: latitude,
//       longtitude: longtitude,
//       address: address,
//       locationId: locationId,
//       openTimeRule: openTimeRule,
//       description: description,
//       phone: phone,
//       avgRating: avgRating,
//       ratingCount: ratingCount,
//     );
//   }

//   static Map<String, dynamic> update({
//     int? id,
//     DateTime? createdAt,
//     String? name,
//     String? ename,
//     String? cover,
//     List<String>? images,
//     double? hotScore,
//     int? price,
//     Map<String, dynamic>? rankInfo,
//     double? latitude,
//     double? longtitude,
//     String? address,
//     int? locationId,
//     List<Map<String, dynamic>>? openTimeRule,
//     String? description,
//     String? phone,
//     double? avgRating,
//     int? ratingCount,
//   }) {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       name: name,
//       ename: ename,
//       cover: cover,
//       images: images,
//       hotScore: hotScore,
//       price: price,
//       rankInfo: rankInfo,
//       latitude: latitude,
//       longtitude: longtitude,
//       address: address,
//       locationId: locationId,
//       openTimeRule: openTimeRule,
//       description: description,
//       phone: phone,
//       avgRating: avgRating,
//       ratingCount: ratingCount,
//     );
//   }

//   factory Attractions.fromJson(Map<String, dynamic> jsonn) {
//     return Attractions(
//       id: jsonn['id'] != null ? int.parse(jsonn['id'].toString()) : int.from(0),
//       createdAt: jsonn['created_at'] != null
//           ? DateTime.parse(jsonn['created_at'].toString())
//           : DateTime.fromMillisecondsSinceEpoch(0),
//       name: jsonn['name'] != null ? jsonn['name'].toString() : '',
//       ename: jsonn['ename'] != null ? jsonn['ename'].toString() : '',
//       cover: jsonn['cover'] != null ? jsonn['cover'].toString() : '',
//       images: jsonn['images'] != null
//           ? (jsonn['images'] as List<dynamic>).map((v) => v.toString()).toList()
//           : <String>[],
//       hotScore: jsonn['hot_score'] != null
//           ? double.parse(jsonn['hot_score'].toString())
//           : 0.0,
//       price: jsonn['price'] != null
//           ? int.parse(jsonn['price'].toString())
//           : int.from(0),
//       rankInfo: jsonn['rank_info'] != null
//           ? jsonn['rank_info'] as Map<String, dynamic>
//           : <String, dynamic>{},
//       latitude: jsonn['latitude'] != null
//           ? double.parse(jsonn['latitude'].toString())
//           : 0.0,
//       longtitude: jsonn['longtitude'] != null
//           ? double.parse(jsonn['longtitude'].toString())
//           : 0.0,
//       address: jsonn['address'] != null ? jsonn['address'].toString() : '',
//       locationId: jsonn['location_id'] != null
//           ? int.parse(jsonn['location_id'].toString())
//           : int.from(0),
//       openTimeRule: jsonn['open_time_rule'] != null
//           ? (jsonn['open_time_rule'] as List<dynamic>)
//               .map((v) => json.decode(v) as Map<String, dynamic>)
//               .toList()
//           : <Map<String, dynamic>>[],
//       description:
//           jsonn['description'] != null ? jsonn['description'].toString() : '',
//       phone: jsonn['phone'] != null ? jsonn['phone'].toString() : '',
//       avgRating: jsonn['avg_rating'] != null
//           ? double.parse(jsonn['avg_rating'].toString())
//           : 0.0,
//       ratingCount: jsonn['rating_count'] != null
//           ? int.parse(jsonn['rating_count'].toString())
//           : int.from(0),
//     );
//   }

//   Map<String, dynamic> toJson() {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       name: name,
//       ename: ename,
//       cover: cover,
//       images: images,
//       hotScore: hotScore,
//       price: price,
//       rankInfo: rankInfo,
//       latitude: latitude,
//       longtitude: longtitude,
//       address: address,
//       locationId: locationId,
//       openTimeRule: openTimeRule,
//       description: description,
//       phone: phone,
//       avgRating: avgRating,
//       ratingCount: ratingCount,
//     );
//   }

//   Attractions copyWith({
//     int? id,
//     DateTime? createdAt,
//     String? name,
//     String? ename,
//     String? cover,
//     List<String>? images,
//     double? hotScore,
//     int? price,
//     Map<String, dynamic>? rankInfo,
//     double? latitude,
//     double? longtitude,
//     String? address,
//     int? locationId,
//     List<Map<String, dynamic>>? openTimeRule,
//     String? description,
//     String? phone,
//     double? avgRating,
//     int? ratingCount,
//   }) {
//     return Attractions(
//       id: id ?? this.id,
//       createdAt: createdAt ?? this.createdAt,
//       name: name ?? this.name,
//       ename: ename ?? this.ename,
//       cover: cover ?? this.cover,
//       images: images ?? this.images,
//       hotScore: hotScore ?? this.hotScore,
//       price: price ?? this.price,
//       rankInfo: rankInfo ?? this.rankInfo,
//       latitude: latitude ?? this.latitude,
//       longtitude: longtitude ?? this.longtitude,
//       address: address ?? this.address,
//       locationId: locationId ?? this.locationId,
//       openTimeRule: openTimeRule ?? this.openTimeRule,
//       description: description ?? this.description,
//       phone: phone ?? this.phone,
//       avgRating: avgRating ?? this.avgRating,
//       ratingCount: ratingCount ?? this.ratingCount,
//     );
//   }
// }

// class TravelTypes implements SupadartClass<TravelTypes> {
//   final DateTime createdAt;
//   final String name;
//   final String fid;
//   final String id;
//   final String? parentId;

//   const TravelTypes({
//     required this.createdAt,
//     required this.name,
//     required this.fid,
//     required this.id,
//     this.parentId,
//   });

//   static String get table_name => 'travel_types';
//   static String get c_createdAt => 'created_at';
//   static String get c_name => 'name';
//   static String get c_fid => 'fid';
//   static String get c_id => 'id';
//   static String get c_parentId => 'parent_id';

//   static List<TravelTypes> converter(List<Map<String, dynamic>> data) {
//     return data.map(TravelTypes.fromJson).toList();
//   }

//   static TravelTypes converterSingle(Map<String, dynamic> data) {
//     return TravelTypes.fromJson(data);
//   }

//   static Map<String, dynamic> _generateMap({
//     DateTime? createdAt,
//     String? name,
//     String? fid,
//     String? id,
//     String? parentId,
//   }) {
//     return {
//       if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
//       if (name != null) 'name': name,
//       if (fid != null) 'fid': fid,
//       if (id != null) 'id': id,
//       if (parentId != null) 'parent_id': parentId,
//     };
//   }

//   static Map<String, dynamic> insert({
//     DateTime? createdAt,
//     required String name,
//     required String fid,
//     String? id,
//     String? parentId,
//   }) {
//     return _generateMap(
//       createdAt: createdAt,
//       name: name,
//       fid: fid,
//       id: id,
//       parentId: parentId,
//     );
//   }

//   static Map<String, dynamic> update({
//     DateTime? createdAt,
//     String? name,
//     String? fid,
//     String? id,
//     String? parentId,
//   }) {
//     return _generateMap(
//       createdAt: createdAt,
//       name: name,
//       fid: fid,
//       id: id,
//       parentId: parentId,
//     );
//   }

//   factory TravelTypes.fromJson(Map<String, dynamic> jsonn) {
//     return TravelTypes(
//       createdAt: jsonn['created_at'] != null
//           ? DateTime.parse(jsonn['created_at'].toString())
//           : DateTime.fromMillisecondsSinceEpoch(0),
//       name: jsonn['name'] != null ? jsonn['name'].toString() : '',
//       fid: jsonn['fid'] != null ? jsonn['fid'].toString() : '',
//       id: jsonn['id'] != null ? jsonn['id'].toString() : '',
//       parentId: jsonn['parent_id'] != null ? jsonn['parent_id'].toString() : '',
//     );
//   }

//   Map<String, dynamic> toJson() {
//     return _generateMap(
//       createdAt: createdAt,
//       name: name,
//       fid: fid,
//       id: id,
//       parentId: parentId,
//     );
//   }

//   TravelTypes copyWith({
//     DateTime? createdAt,
//     String? name,
//     String? fid,
//     String? id,
//     String? parentId,
//   }) {
//     return TravelTypes(
//       createdAt: createdAt ?? this.createdAt,
//       name: name ?? this.name,
//       fid: fid ?? this.fid,
//       id: id ?? this.id,
//       parentId: parentId ?? this.parentId,
//     );
//   }
// }

// class TodoLists implements SupadartClass<TodoLists> {
//   final int id;
//   final DateTime createdAt;
//   final DateTime? time;
//   final String? priority;
//   final Map<String, dynamic>? members;
//   final String? description;
//   final String? category;

//   const TodoLists({
//     required this.id,
//     required this.createdAt,
//     this.time,
//     this.priority,
//     this.members,
//     this.description,
//     this.category,
//   });

//   static String get table_name => 'todo_lists';
//   static String get c_id => 'id';
//   static String get c_createdAt => 'created_at';
//   static String get c_time => 'time';
//   static String get c_priority => 'priority';
//   static String get c_members => 'members';
//   static String get c_description => 'description';
//   static String get c_category => 'category';

//   static List<TodoLists> converter(List<Map<String, dynamic>> data) {
//     return data.map(TodoLists.fromJson).toList();
//   }

//   static TodoLists converterSingle(Map<String, dynamic> data) {
//     return TodoLists.fromJson(data);
//   }

//   static Map<String, dynamic> _generateMap({
//     int? id,
//     DateTime? createdAt,
//     DateTime? time,
//     String? priority,
//     Map<String, dynamic>? members,
//     String? description,
//     String? category,
//   }) {
//     return {
//       if (id != null) 'id': id.toString(),
//       if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
//       if (time != null) 'time': time.toUtc().toIso8601String(),
//       if (priority != null) 'priority': priority,
//       if (members != null) 'members': members,
//       if (description != null) 'description': description,
//       if (category != null) 'category': category,
//     };
//   }

//   static Map<String, dynamic> insert({
//     int? id,
//     DateTime? createdAt,
//     DateTime? time,
//     String? priority,
//     Map<String, dynamic>? members,
//     String? description,
//     String? category,
//   }) {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       time: time,
//       priority: priority,
//       members: members,
//       description: description,
//       category: category,
//     );
//   }

//   static Map<String, dynamic> update({
//     int? id,
//     DateTime? createdAt,
//     DateTime? time,
//     String? priority,
//     Map<String, dynamic>? members,
//     String? description,
//     String? category,
//   }) {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       time: time,
//       priority: priority,
//       members: members,
//       description: description,
//       category: category,
//     );
//   }

//   factory TodoLists.fromJson(Map<String, dynamic> jsonn) {
//     return TodoLists(
//       id: jsonn['id'] != null ? int.parse(jsonn['id'].toString()) : int.from(0),
//       createdAt: jsonn['created_at'] != null
//           ? DateTime.parse(jsonn['created_at'].toString())
//           : DateTime.fromMillisecondsSinceEpoch(0),
//       time: jsonn['time'] != null
//           ? DateTime.parse(jsonn['time'].toString())
//           : DateTime.fromMillisecondsSinceEpoch(0),
//       priority: jsonn['priority'] != null ? jsonn['priority'].toString() : '',
//       members: jsonn['members'] != null
//           ? jsonn['members'] as Map<String, dynamic>
//           : <String, dynamic>{},
//       description:
//           jsonn['description'] != null ? jsonn['description'].toString() : '',
//       category: jsonn['category'] != null ? jsonn['category'].toString() : '',
//     );
//   }

//   Map<String, dynamic> toJson() {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       time: time,
//       priority: priority,
//       members: members,
//       description: description,
//       category: category,
//     );
//   }

//   TodoLists copyWith({
//     int? id,
//     DateTime? createdAt,
//     DateTime? time,
//     String? priority,
//     Map<String, dynamic>? members,
//     String? description,
//     String? category,
//   }) {
//     return TodoLists(
//       id: id ?? this.id,
//       createdAt: createdAt ?? this.createdAt,
//       time: time ?? this.time,
//       priority: priority ?? this.priority,
//       members: members ?? this.members,
//       description: description ?? this.description,
//       category: category ?? this.category,
//     );
//   }
// }

// class TripMembers implements SupadartClass<TripMembers> {
//   final int id;
//   final DateTime createdAt;
//   final String? userId;
//   final bool? isConfirmed;
//   final int? lastSeenMsgId;

//   const TripMembers({
//     required this.id,
//     required this.createdAt,
//     this.userId,
//     this.isConfirmed,
//     this.lastSeenMsgId,
//   });

//   static String get table_name => 'trip_members';
//   static String get c_id => 'id';
//   static String get c_createdAt => 'created_at';
//   static String get c_userId => 'user_id';
//   static String get c_isConfirmed => 'is_confirmed';
//   static String get c_lastSeenMsgId => 'last_seen_msg_id';

//   static List<TripMembers> converter(List<Map<String, dynamic>> data) {
//     return data.map(TripMembers.fromJson).toList();
//   }

//   static TripMembers converterSingle(Map<String, dynamic> data) {
//     return TripMembers.fromJson(data);
//   }

//   static Map<String, dynamic> _generateMap({
//     int? id,
//     DateTime? createdAt,
//     String? userId,
//     bool? isConfirmed,
//     int? lastSeenMsgId,
//   }) {
//     return {
//       if (id != null) 'id': id,
//       if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
//       if (userId != null) 'user_id': userId,
//       if (isConfirmed != null) 'is_confirmed': isConfirmed,
//       if (lastSeenMsgId != null) 'last_seen_msg_id': lastSeenMsgId.toString(),
//     };
//   }

//   static Map<String, dynamic> insert({
//     int? id,
//     DateTime? createdAt,
//     String? userId,
//     bool? isConfirmed,
//     int? lastSeenMsgId,
//   }) {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       userId: userId,
//       isConfirmed: isConfirmed,
//       lastSeenMsgId: lastSeenMsgId,
//     );
//   }

//   static Map<String, dynamic> update({
//     int? id,
//     DateTime? createdAt,
//     String? userId,
//     bool? isConfirmed,
//     int? lastSeenMsgId,
//   }) {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       userId: userId,
//       isConfirmed: isConfirmed,
//       lastSeenMsgId: lastSeenMsgId,
//     );
//   }

//   factory TripMembers.fromJson(Map<String, dynamic> jsonn) {
//     return TripMembers(
//       id: jsonn['id'] != null ? int.parse(jsonn['id'].toString()) : 0,
//       createdAt: jsonn['created_at'] != null
//           ? DateTime.parse(jsonn['created_at'].toString())
//           : DateTime.fromMillisecondsSinceEpoch(0),
//       userId: jsonn['user_id'] != null ? jsonn['user_id'].toString() : '',
//       isConfirmed:
//           jsonn['is_confirmed'] != null ? jsonn['is_confirmed'] as bool : false,
//       lastSeenMsgId: jsonn['last_seen_msg_id'] != null
//           ? int.parse(jsonn['last_seen_msg_id'].toString())
//           : int.from(0),
//     );
//   }

//   Map<String, dynamic> toJson() {
//     return _generateMap(
//       id: id,
//       createdAt: createdAt,
//       userId: userId,
//       isConfirmed: isConfirmed,
//       lastSeenMsgId: lastSeenMsgId,
//     );
//   }

//   TripMembers copyWith({
//     int? id,
//     DateTime? createdAt,
//     String? userId,
//     bool? isConfirmed,
//     int? lastSeenMsgId,
//   }) {
//     return TripMembers(
//       id: id ?? this.id,
//       createdAt: createdAt ?? this.createdAt,
//       userId: userId ?? this.userId,
//       isConfirmed: isConfirmed ?? this.isConfirmed,
//       lastSeenMsgId: lastSeenMsgId ?? this.lastSeenMsgId,
//     );
//   }
// }
